pub_hdrs = hxx{**}

./: $pub_hdrs

# Install into, say, /usr/include/ recreating subdirectories (the public
# headers are included as <stdexec/...> and <exec/...>).
#
hxx{*}:
{
  install         = include/
  install.subdirs = true
}
